# Exerc√≠cios - comparando LightGBM e XGBoost

In [3]:
# bibliotecas
import numpy as np 
import pandas as pd 
import lightgbm as lgbm
import xgboost as xgb
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, StratifiedKFold, cross_val_score
from datetime import datetime
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter(action='ignore', category=FutureWarning)

In [4]:
# dataset
df_census = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', header=None)
df_census.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',
                  'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 
                   'income']
df_census.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [5]:
df_census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [6]:
# EDA
df_census = df_census.drop(['education'], axis=1)
df_census = pd.get_dummies(df_census)
df_census = df_census.drop('income_ <=50K', axis=1)
df_census.head()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,...,native-country_ Puerto-Rico,native-country_ Scotland,native-country_ South,native-country_ Taiwan,native-country_ Thailand,native-country_ Trinadad&Tobago,native-country_ United-States,native-country_ Vietnam,native-country_ Yugoslavia,income_ >50K
0,39,77516,13,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,50,83311,13,0,0,13,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,38,215646,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,53,234721,7,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,28,338409,13,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
#features e labels
X = df_census.iloc[:,:-1]
y = df_census.iloc[:,-1]

### ToDo 1
Separe o conjunto de features com suas respectivas labels em conjunto de treino e teste na propor√ß√£o de 70%-30%. Use random_state=42 para reprodutibilidade.

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### ToDo 2

Treine um modelo LightGBM e um modelo XGBoost nos dados acima gerados. Utilize a vers√£o padr√£o de ambos os modelos. Use a biblioteca datetime para computar o tempo de treinamento de cada modelo. Avalie ambos usando a acur√°cia.

In [24]:
import datetime
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

# Treinando o modelo XGBoost
start = datetime.datetime.now()
xgb_model = XGBClassifier()
xgb_model.fit(X_train, y_train)
end = datetime.datetime.now()
print(f"Tempo de treinamento XGBoost: {end - start}")

y_pred_xgb = xgb_model.predict(X_test)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"Acur√°cia do modelo XGBoost: {accuracy_xgb}")

Tempo de treinamento XGBoost: 0:00:00.929006
Acur√°cia do modelo XGBoost: 0.8692803767018119

In [11]:
# Treinando o modelo LightGBM
start = datetime.datetime.now()
lgbm_model = LGBMClassifier()
lgbm_model.fit(X_train, y_train)
end = datetime.datetime.now()
print(f"Tempo de treinamento LightGBM: {end - start}")

y_pred_lgbm = lgbm_model.predict(X_test)
accuracy_lgbm = accuracy_score(y_test, y_pred_lgbm)
print(f"Acur√°cia do modelo LightGBM: {accuracy_lgbm}")

Tempo de treinamento LightGBM: 0:00:00.123503
Acur√°cia do modelo LightGBM: 0.8746033370867028

### ToDo 3

Modifique a fun√ß√£o grid_search, vista na aula de XGBoost, para otimizar os parametros de ambos os modelos. Agora, ela precisa permitir receber, al√©m do conjunto de treino e respectivas respostas, o conjunto de teste e respectivas respostas.

In [26]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, KFold

def grid_search(params, model, X_train, y_train, X_test, y_test, random=False, kfold=5):
    
    if random:
        grid = RandomizedSearchCV(model, params, cv=kfold, n_jobs=-1, random_state=2, scoring='recall')
    else:
        grid = GridSearchCV(model, params, cv=kfold, n_jobs=-1, scoring='recall')
    
    grid.fit(X_train, y_train)

    best_params = grid.best_params_
    best_score = grid.best_score_

    print("Best params:", best_params)
    print("Best score: {:.5f}".format(best_score))

    y_pred = grid.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_pred)
    
    return best_params, best_score, test_accuracy

### ToDo 4
Otimize os hiperpar√¢metros que achar conveniente. Compare o tempo de treinamento e a acur√°cia de cada modelo

* Par√¢metros XGBoost -> [link](https://xgboost.readthedocs.io/en/stable/parameter.html)

* Par√¢metros LightGBM -> [link](https://lightgbm.readthedocs.io/en/latest/Parameters.html)

In [28]:
# Par√¢metros para otimiza√ß√£o
lgbm_params = {
    'learning_rate': [0.01, 0.1, 0.3],
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7]
}

xgb_params = {
    'learning_rate': [0.01, 0.1, 0.3],
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7]
}


# Otimizando XGBoost
best_xgb_params, best_xgb_score, xgb_test_accuracy = grid_search(xgb_params, XGBClassifier(random_state=2, scale_pos_weight=10, verbosity=0, use_label_encoder=False), X_train, y_train, X_test, y_test)
print(f"Melhores par√¢metros XGBoost: {best_xgb_params}")
print(f"Melhor acur√°cia de valida√ß√£o cruzada XGBoost: {best_xgb_score}")
print(f"Acur√°cia no conjunto de teste XGBoost: {xgb_test_accuracy}")

Best params: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 50}
Best score: 0.96580
Melhores par√¢metros XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 50}
Melhor acur√°cia de valida√ß√£o cruzada XGBoost: 0.9658033106134372
Acur√°cia no conjunto de teste XGBoost: 0.678063261336882

In [29]:

# Otimizando LightGBM
best_lgbm_params, best_lgbm_score, lgbm_test_accuracy = grid_search(lgbm_params, LGBMClassifier(random_state=2), X_train, y_train, X_test, y_test)
print(f"Melhores par√¢metros LightGBM: {best_lgbm_params}")
print(f"Melhor acur√°cia de valida√ß√£o cruzada LightGBM: {best_lgbm_score}")
print(f"Acur√°cia no conjunto de teste LightGBM: {lgbm_test_accuracy}")

Best params: {'learning_rate': 0.3, 'max_depth': 5, 'n_estimators': 200}
Best score: 0.66383
Melhores par√¢metros LightGBM: {'learning_rate': 0.3, 'max_depth': 5, 'n_estimators': 200}
Melhor acur√°cia de valida√ß√£o cruzada LightGBM: 0.6638303617454772
Acur√°cia no conjunto de teste LightGBM: 0.8659023441498618

#### ToDo 5

Apenas para LightGBM. Use os parametros encontrados pelo boosting e treine 4 versoes diferentes usando os diferentes tipos de boosting (gbdt, goss, dart e rf).

* Obs: quando boosting_type=rf, use dois parametros adicionais

    -> bagging_freq=1
    
    -> bagging_fraction=0.8

In [17]:
boosting_types = ['gbdt', 'goss', 'dart', 'rf']
lgbm_models = []

for boosting_type in boosting_types:
    params = best_lgbm_params.copy()
    params['boosting_type'] = boosting_type
    
    if boosting_type == 'rf':
        params['bagging_freq'] = 1
        params['bagging_fraction'] = 0.8
    
    model = LGBMClassifier(**params)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    
    lgbm_models.append((model, accuracy))
    print(f"Acur√°cia do LightGBM com boosting_type={boosting_type}: {accuracy}")

# Imprimir a acur√°cia de todos os modelos treinados
for i, (model, accuracy) in enumerate(lgbm_models):
    print(f"Acur√°cia do LightGBM com boosting_type={boosting_types[i]}: {accuracy}")

Acur√°cia do LightGBM com boosting_type=gbdt: 0.8738867847271983
Acur√°cia do LightGBM com boosting_type=goss: 0.8713276691575391
Acur√°cia do LightGBM com boosting_type=dart: 0.8698945644385301
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
Acur√°cia do LightGBM com boosting_type=rf: 0.8610912068789026
Acur√°cia do LightGBM com boosting_type=gbdt: 0.8738867847271983
Acur√°cia do LightGBM com boosting_type=goss: 0.8713276691575391
Acur√°cia do LightGBM com boosting_type=dart: 0.8698945644385301
Acur√°cia do LightGBM com boosting_type=rf: 0.8610912068789026

In [ ]:
#GBDT

In [ ]:
#Goss

In [ ]:
#DART

In [ ]:
#RF